---
version: '3'

services:
  jsonlint:
    container_name: jsonlint
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/jsonlint:latest
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/jsonlint
